name: CI/CD for Python

on:
  push:
    branches:
      - master  # Déclencher le pipeline CI CD à chaque push sur ma branche master 

jobs:
  build:
    runs-on: ubuntu-latest # Indique la plateforme sur lequel le script va s'executer. 

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2  # Utiliser l'Action git pour extraire le code source.

    - name: Setup Node.js
      run: 
    # Configuration de Node.js 16
        nvm install 16
        nvm use 16

   # Recuperer le code source et de le rendre disponible en s'assurant d'avoir une version à jour : pret pour la compilation, test, déploiement 


    - name: Exécuter le script Python
      run: python hello.py  # Exécuter le script Python.


